apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ksvc-concurrency-scale-to-zero
  namespace: production
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/metric: "concurrency"
        autoscaling.knative.dev/target: "10"
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "0s"
    spec:
      containers:
        - image: ghcr.io/knative/autoscale-go:latest
