apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: autoscale-go
  namespace: production
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"  # Always keep 1 pod running
        autoscaling.knative.dev/target: "10"   # Concurrency target per pod
    spec:
      containers:
        - image: ghcr.io/knative/autoscale-go:latest
